version: '3.9'

services:
  java_app:
    container_name: java_app
    image: devops:1.0.0
    build: .
    ports:
      - 8090:8090
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/apiusuario
      - DATABASE_USERNAME=root # Cambia esto al usuario que corresponda
      - DATABASE_PASSWORD=secretmysql # Cambia esto a tu contraseña de MySQL
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=apiusuario
      - MYSQL_ROOT_PASSWORD=secretmysql # Cambia esto a tu contraseña de root de MySQL
    ports:
      - '3306:3306'
